apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-seaweedfs-s3-config.yaml
  - sealed-seaweedfs-iam-config.yaml
  - sealed-seaweedfs-jwt.yaml
  - sealed-seaweedfs-admin.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ingressroute-admin.yaml
  - ingressroute-s3.yaml
  - pdb.yaml
