---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-s3-config
  namespace: seaweedfs
spec:
  encryptedData:
    seaweedfs_s3_config: AgBI7+2yW2U5CLtHP7qDon0lN6OBALpktkNVJ23Vt1IRb/brCv/idmNkQHS/qVbjVM6Z3408Lx4Pz8QZ4eQEtE9aHF3grd03EAbDD9fmqxvgG+FYEz5Or1gsPeXhsvwDore4RQK2FSDZhzoJj3tClD8EYn4rX3bXN8bNVVN7oUhI0BVetKqiJvysP6/MM/PmOlP5Rr9pXKq93Hjx5Tt25qBYnPldFmWbKwQMEZXvFjKBjdeBKcH7zkv7Uqugjd/KH3zb9DsSF4FX3SHjPAvaPW2lWfU0E5YEClNP/XvRJ0wMTarloo/JApp6ZTBPM2SYACL2kmuY/3QsO+RXgvEGbsFs8ZWMhNvki6f3noC1aRhrFUFsmF250q/CxAFgnyUc0ozcEBsHjY6HVaAN1uLyE3mBhqm13LwYGg/J4HeHQ4WbS5ip1t/4AbUIKCawF3JBAqiOWOSueeXeVC5bZHBwGvi0xpDBsYyuc6WGKKD84tdTRIu3OBaOODByDU87RQonhQwt0wZWuFCPBbVrXGvMxBO7QwO/HAUO4jDNRyIC5sms+lbkIWhAQl96iRu634HowvELXR3n9ibLLiDZjUmPmO7fx/wwU7f+L/Qm2HNTicTr1kcXQaPJX1rbm9/4u3sk9KCprFTfIBlCqeLGqDW6tNFbhtkXiV5+oew9Q8zeNM1oLZE1pBfOG0IIFsyLoG85Lm5GXiZs8eWtTeTyaeG9tTvI4R9MQApW46jUrUIFCiCU9tGH3FsodRTUNlc4/b+jHKv35YfIh6tr4ILs/YqnMrnoYk2ruBfzp98tZpun6lS13UmQbm4Ys5t4tnzlz1Ezd+3aMHfZ+N2RH2sl1jQcCtxs+IUaP/A3I+7Zc6Won42bVrMj3NGsvaJrTb23Q1kRKwIZswQpl3DfN7aC61gGooce9TihIc0YsOhpd3R0nBgLZsYTaQddWIueIpRrSyZKZ0s0f9F9XoayX98RcVYEzGaNE7g2JVTHYqIaEgJzpHYe6/YuVjJ7Wua6w8J6SxI0Ca7mnzzG3IhCbh5fFWtTs3WqLkdi4vrpTyF6Qj9z0BHIBc60Pe8yaMJZhRIDIy04Re7LC3MbZFE001DZ+SMW2ugkjvSyXx7COSpkmr5m4VpMUGZ3HdayswTnVIvUF4Uzse9qEC93epHJAQT7yauutjCGL1TaJcEqXD+EhNWj77T1BVmTljDHMOLMosyPcUW09h1IJs3ijT6UHaWzjNLOPECRyRvkWmS8Cg==
  template:
    metadata:
      name: seaweedfs-s3-config
      namespace: seaweedfs
    type: Opaque
