---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-s3-config
  namespace: seaweedfs
spec:
  encryptedData:
    seaweedfs_s3_config: AgCqkRUrEDelw+YPXNqWfFgSBBQ+eMkyh0/VaNb7hlPjlycZ/ROmvGDwSkxyXGAq4oPpEW4PdApVD0YAkhgZUoP80bQErkRZksVvG/oOSnpnDMjuSQhXQgLFZmtXomj83Ffs9nL9f78K2sgvGOinNF9RzPjSrs6sOXSqSY1IJb8anKTq8gP2X+3ALDf/fsQUQDcQ6tJLlAbZk/3Caekzp3lWG2qwFuv1a1heprHCfrPK/yOTQJMyE7gL4ZDIS8qhBtN0SwzkzSn4qufNVymPTXvZDUeaVKGTFHeAMEtQjNFU4O3TStRSGXMe6wpjg3mReAptFFoc70Q4yNJ921jWJzxKmclBU8GOpVkIh6S4o9AU3Feu1HBugaL6HVwG8OZY+E2ImSUzAyYUr1AtOY0pCC2rmveXwo3+h7UZJERaAN6I4AJ9NLAmP+k+jsn+qviP6xRr3qomVnI4J1Lj03cNFWIvWyJLPX3BJo7sxk46A+zrJ69ds3PsC6fo2RglHCVStbGIDAmba8tB3Tj5aOm1cjuYAgQOoxnZuXq6S5X6QOT8ng5qtyQP92AKyojL1LlXkDfv9t2my8VrWHG4erh3iuX1kkaWA0dnocVW9P5RA9X6Yy0nf66MRPewqqcUAltz9qhKHVnZsGcpALdSh012BylROI3FRFOvpVjl9vtqg7Lz33hTLeB7X94hKuPrGK632gwB6Uq0sxp842m3gzp8FIVBB8epQWL+HZvDyH2nJMjO25+lOKd0DWbwi8vQAhuw/E6b3Y+z1mrPmjuKrFyrXKOKnOlI+lRwBeOlCajJTbvZjYe+sV4KMm4gzR0OvTXVpD9ASPyvI4PJwAxGEIGJYsIEMAVVlWXFv79vf8t362T4CdrfQfBE1DSmasYTQLNh6lxBEIjQRvPUJeIP879WuQ5R/X+eRnNfhLdOmEhlKP+nK22rgKToAzcT0KUAkbTvpmp0X+6rooVIa4SiWRWKaemyR5HPSFa1RabmRWgT10w/ZG6kQ7wQSbtr+DoDIMPVpPEnQbimL9l2gBceJPzfUcj3FtdZ7jn7ivtOx7x5F/b+Iu/eXGiG8yYdWhqWJnQhKDc9by6jXAat3xSRpgyqYiW460/gRHjLtCpkrxm4h0aSf2L1bO+knq9yGRPnZettAbI+o5nobQd4pnoTU1+yy9FmZgWQ1UqR/9cj9asjMRDyhXICjlfisQT535B6BvlUTyMLwIUP+/LXctz0dkcHgg==
  template:
    metadata:
      name: seaweedfs-s3-config
      namespace: seaweedfs
    type: Opaque
