---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-admin
  namespace: seaweedfs
spec:
  encryptedData:
    admin-password: AgCrUkJxBS+Y03V1IkPP+Es6U7d9nNsyG0EE9hDzuhTWGdoFor9L6yoa16ThmIixft7/Ui5hO77jLn/QEMcN9YmePavOhDVc+gtvCT7m7jUxJb0TyHa7kZaqPE8/odqmB/BatXlqZBm0PqGe+qnYjsWsLoae/Ib8KtJM2Vsh6OD7emX7P4bMweJwrDBtXUO8AWcG41hsWQxCUGGHwyVyEAGpXyQupsi6KBzSSRmpRvUGMgRSdtN22XGemavV2cFX7mvsAlYGbFusNyqcVobQeGVLnxoqMeixnLdbAT2m7RyjbxTQhhHp9+y+oEs+t3GByueaU4iZlkVJlSrPQB/6o8vmXo9i62RunjU1Tdzdj3mA56g/TVNQrvwcL/2AqE80RFD2la2HCi7Nyf7WrzFMbYY5F3DEv8/SLQmqZfUKX5ikg8kbD1n3vDVNnRBk46UhwECmY+PBTg6IA/wMDQudcIUiIEk18H/xt8SmFqdbu/ymglbBPbU23eyCpPI3FR19QxDjJ4chyIL2fbKUCa2FIDXETjYJGiOpJdWtg99p2WcVBd/pF/dMlQkFY9Zt3xpnrqvY0WtDgle/Ca2Qh2oG59qhjSeguvsmF+L9SyOZU1XBYFoYOO1D4a/5B0vDPMeWwuZFWtAjtEP6dMhxI8/BaCRwKilQ4E2GV3tHI5gOLupZCSqk6JJ2BbM1Td/e/LYzxzjNcjigxxLmQgdQyGxv4oZchyrQJy60NQXse5zI1zu9fg==
    admin-user: AgBqY2TT5zGLa8HRKmI/6mvtkrGao7PczH/tnHjsNKihzFG2Mv0i3Llxr28ll472yH7c5Q3akxObL5v3BP0FXZjpMHE075Rrl0aknCxSUjoD1bllryBqL8cPGbs5vrKoLFe5K+6kKhnc+irg1Q06mHSQ6AfPKfoDDtPF5qCn6I8/P/HoAo3BLhW4BiTvtLBaHHJ5DkNT+obfGy/ZCKB49H4hVjLoqALZwuTyrDfVPPl7ApNXmuUfbxgTW06SN4Z2G0lW0X6SVhokfjUkjfcqwe3i5z5kWBZzJq2c0DbRlsZaEcF7BpD4OtLxdjx2C0mx5r9FL/1wv84NJ6R8kNXnV/yh9UtNC/OxGdp0CtodVmMNzGGobXtB4SbKY7pJwHQ7+/Hm58GmL3K7lFuUYeYZrr1ANcx/JAKMWgwE8pR8Rbi7vvCplA42mkEyPmfyD8Sv3stwTN0WoB+e5bDDiRNILuSMR6BJi6GMl0Fea7eXUjs1MoReU/xV7B5LI+QpM9dMLvRhTIeJd9GprnH/mC6VpIQCVUAPGGU1KHUU7pPLV+SB/+pa8RG0mj3RCvawJ4ERLeLU4QMpcIiLeU9CbDpRsQuWjIJoA+hVBS/pc48QojfdXcVUW+mWH+eg1ROOmLnog9GyOGip2uGMoyx+EGTzJfyi9scqZ10YqMi0SebcLJyk6kB1e3eGMOxGjrJGOZ3TGv0d6YnjBA==
  template:
    metadata:
      name: seaweedfs-admin
      namespace: seaweedfs
    type: Opaque
