---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-jwt
  namespace: seaweedfs
spec:
  encryptedData:
    jwt-signing-key: AgCCImwMhpUdcjwPxKkpq01Yokdaoo3xF1GVOlzPBFkVHYSYFMVMKZLYgi5BtLildB+ACl0T25hfaK8bDvwnDBfyqTYPY2eAoqLTo8POTC5FcxlBYcoH+qSfXB6R7aj6qLgVbdOOxJqISNyNmznZfLHzp8o95Dqle8owC9M39XOGT8wCyVyugQdiBMZmx/BIqQyd4Rj+IdCNK/deo1R8258drzkfRZgdlAdXTO4t0bFncMOGgEFMHvzBzjSwANNUmVXWi+WDNNiy4wQhw0FNp0Z1s5wtpDIxZI+F1o/AUxpOsb7u4OgmvQb58XjS7QYnMFGECdlus6lBpRcJFiDNFOFeL4DThRm0h6N4/FFlW+VHHolqOnWxAeCNtXJsJ7Ey5izyZLIlQ6bN+VmpDRHj66q5Ac5Bj71uFCSjVnrPUuejSwNyFLWS+4uQ+Iq1E/dMoYgn1R3gHzS3IlFYPoW5xpqeODweWdOEdOqjHvYXdNWl47YdHK8vr8sW3uvMQfQi79dhYHMbgYdd/MNZOlgJgQHbBMnOijXZXSTQ7b2GDZsRqSWZKIWdlB7iJaHAqbzAr1HwbnyHCDqy6B6j+RyWJXp2oPV9B7zc2IE6cEdlRP++PYJe/o7hvrsBLH13CDTsTkzutPTJjbblcLgRDAC24Wcd6ODSFULEOjukO3th8Dui0bqYOPjYP0P/14+4hKaS6d07E8OONWmfQ4tryKzH5ehTe+sq8CnNqc56G/XsGiDfXlgyT9XeHc/mGGyl
  template:
    metadata:
      name: seaweedfs-jwt
      namespace: seaweedfs
    type: Opaque
