apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data

    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: traefik-cloudflare
            key: api-token

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    certResolvers:
      letsencrypt:
        email: arslane.bahlel+claudeai@gmail.com
        storage: /data/acme.json
        caServer: https://acme-v02.api.letsencrypt.org/directory
        dnsChallenge:
          provider: cloudflare
          resolvers:
            - "1.1.1.1:53"
            - "8.8.8.8:53"
