---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-cloudflare
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgAbZZTZSpHL24sXEnXC3XI5mBtNYjGR4gSl71KKIsGEzJgTybvjM+wXFvHAlj+wW+wjYuofpP+x8+UQ2MPBE/eltdlSDKRZOc9igN7AbgPa4s10SFpEpvTlVvkqV4D8WMxnGO8LF+ommqFWOyBb2HleX3qt+PdICBuyvVlhBVujnYcuVpVW1jVnXkQNv5HEwCU3BCKTZ9hvmDqXDz33sK1lmbFwMlbX8AWmC0bPgvTdneXLM9VHufP6sTy9FpH4lwvK9NpQc44WiSaG4ZlZizT8oRxXKr+UxFKKioc+a26NOJvGBMoeDWeBc0B9WeNBPaKyq8LbygH2oSpDpRDBhQy7a2027mW7K/iSS007wplNdVrkkE3cWu7QNHCDyKC7hR9RGneqzWn9gA3S22kQE7ZQFiSHhRuPOQRJjxtBiwbRwDpawmJnTLzz14HqTJKnbNuWnO1OF09V7gfmQC/tewADlvFiePdT6KGnUwlL/DqEQ55Q/bTPqr1Ie2hENrFi2ECP+pVzPEPucrHYCgXDRULgPAimaIf3SgtjNwlmmCdQAlOGrfm2Pd0MceRfgujK/CZMBAJlztxhAcEkszzDCLyJTciRVY3pZXao+gBKJKuwyWqcw9sC7Bd1MlfnyQgsXpPP1DHTYJGu6i8XYLcM0WATbVmULIugWAJEYkCioIOjRwN4+g56oI3QWorBcvXgb/Ne61lPo0kFIOWZ2/Yux54UNn2KgRpgjUMpAQ/Su+jXPdbPnhTnnV9xLw1DRmnAx4zgLVDppw==
  template:
    metadata:
      name: traefik-cloudflare
      namespace: kube-system
