apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  int.edgedatalab.override: |
    hosts {
      10.43.138.80 auth.int.edgedatalab.com
      10.43.138.80 garage.int.edgedatalab.com
      10.43.138.80 grafana.int.edgedatalab.com
      fallthrough
    }
