apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  int.edgedatalab.server: |
    int.edgedatalab.com:53 {
      hosts {
        10.43.138.80 auth.int.edgedatalab.com
        10.43.138.80 garage.int.edgedatalab.com
        10.43.138.80 grafana.int.edgedatalab.com
        10.43.138.80 dagster.int.edgedatalab.com
        10.43.138.80 s3.seaweedfs.int.edgedatalab.com
        fallthrough
      }
      forward . /etc/resolv.conf
    }
