apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-admin-token.yaml
  - sealed-garage-ui-oidc.yaml
  - pvc-data.yaml
  - pdb.yaml
  - service-headless.yaml
  - service.yaml
  - statefulset.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
  - ui

configMapGenerator:
  - name: garage-config
    namespace: garage
    files:
      - garage.toml
