apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-admin-token.yaml
  - pvc-data.yaml
  - pdb.yaml
  - service-headless.yaml
  - service.yaml
  - statefulset.yaml
  - servicemonitor.yaml
  - ui
