---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-ui-oidc
  namespace: garage
spec:
  encryptedData:
    client-secret: AgCwRCcyf7jLoaM9cgYh7VThjuFNIDgo5jtxQEO9lxCsyJ3bQ35wlt4uqhpJ6F7fLZXmNpSKpo4W9XcgLeCpm0pPg9hYvv2RlZthg6RexIGpESrzR4sJkFuSg9QNxcXlI8AeFxzFLU6RHOk4Hv7vv9iC2kKiwpKOFV9rKaUlTHvKiCkQEuu5eUUgpVCTa9PQCsdwORGhk8gguc8N+4orTegQYaXEVjfJH+R2tgxbRRfoIOFnTsYg0rXRMShvOVtQshG9TUcB1I8zGr93qfr5lELRTSDn90ZyVACdikYKWIz/zhATYKu62BWRA5aigmWv/dO46oiq1a8kpbVi/uTAGGMWKVXmbRuyIkS25cEKvTLJwpRAIr9DGAhLykI2hFbXdY+4FlHTLmzfxIAaPufcptB2VYIoGXnu/iz/N9a9UAEli2055HHXrr7R4xHc23mALHIwPNajDfb2CxMYDROYi3NEAqyA2uPMa+442cRXlaqOruuIUsWp1Keqvc6iEPsoPp67GKiqgGKxGkMLXezcXyTVZHj36MS6G8FyYY5QXZbOvmSzLyrOuSWyFl+x5mB87WIZ6Fg5EWmHWgHDsS7aTd6F3G3HdqUDe0pSka0XrUUh6TB9SsFK1wjXHKHeL8DZForlk/hPBj83g7aiGCQ1JUjoTRFDX/6G6YabGMyEniJ3CMD0vdyz0r1dvrKiEiApTb7PN9Ouw7scUrWUACz3mSykC2/iqNW3Dv1KYEPmtMk4EN4HfModxIr2l4ly1cQW9EDZW0pxmeQ4M4acyyBopT91
  template:
    metadata:
      name: garage-ui-oidc
      namespace: garage
