---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-ui-oidc
  namespace: garage
spec:
  encryptedData:
    client-secret: AgA5hcO3q3Ow64vyhnL+X6o0xNcyof1SP15g2GVmQxPgl/RfF3VmzZn6HDAfHGStPoeQOpvtZr3w27I2v3mwRIEcnLmLK897YuhFPvCcYxOYGmL/RFd7beqQ1wa9AF5CKCAoLi4wchvxts4L4igNKY80ejBf8pcYPO4lFOk9cGrhhWLE8OFt1lRIGeADshy/1fVC8hFIFWdUzlFVqTJaLSJ1uBMtyF2afxAfFzS3tOmOB62DIkCUVPXlX2Pc4xquJDxKNfYhpt2xsTvq6Hny1tLBssAIY01SnSglGW6nUyurUAvc9zLXea0pEWpXtk9FbQJ0WPhji1J9drBEM9KW6o6D4sdcL3M47lF62VepupDvCPTWCD0daUhHfQiuEnAW9uzdgV9AxUKFZl0QUgUJ0iZMy5X3ygoNJuo8Lf2rRpL34VQxbOSSiilVBKU3LPPJU5dV7+a8T461HVd9EAC+A/FITg6ibz1BLbFn3eelowCQroa/cNHkKfJ9Eqryj6ppycYlV5D97uTl3Yl93zduzJVxK+883YL1A/44u5BGsvzPU/HyhUWmbt1rQNb3j8Y4h49ZMQoAMn46SWtHYxGchgd8vhfHf5EbZOmwlC6wlO31CYSDb8Ecu/xopGHCFHHGViHj11rmTKGWtUvSfSqWORLCbiesjJXjSpM/ZZuz/GVwUv7KCmZwUXHeRPpEpjm1B2ATyqnRNapo1ixWK6aN9zBmXAwFXLQ4780M+roKWSXvbvm/vsYQt/jTapG1eUCzy8pNiUvjxw9BwKw8EaMypjaF
  template:
    metadata:
      name: garage-ui-oidc
      namespace: garage
