apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-lakekeeper-pg.yaml
  - sealed-lakekeeper-encryption.yaml
  - sealed-openfga-datastore.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - podmonitor.yaml
