---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakekeeper-pg
  namespace: lakekeeper
spec:
  encryptedData:
    postgresql-password: AgCo49jp2I18H8h6sMucPCfuALxL7YP30ArgEt6ZUzkRCwHKTEucjF2DZP69vdygVY8NP37vxBDMQDshgHC6KTWQtKGO64YNDQsd7vJJTtvUzYGHDnG9zCmNCrTs7lG+OfJewNPuJ0z1HGElFlPMbMUz9ZwhCf6t0WQiPOEK1Np0kwviTsZoGuPTULZ3XADscWEa6ezrtYJ7Cnc0dpeCRIUVpuoZ9950oh9FC1sgrnZp4Cg7jx1AmoMKvpdY18eOb3K8cmw78kNL/LDNkvB4xmtYp1e3ExST4gbsZ0GsDOO39+Jt9eydrqE8z+pEhtv6wB1Toq8uFQUesLbAWajRaThfChKrn+GZxca70ZjJvAb1PexKXwCNJrq/d2NCdefsCssDyehIt4rZh8se+YeEViKNObDWuvdFvhvmSMOTBXbQVI3NB3xpvxkN0pp0SP2njgHr8yhCNDGYk2JCsQ08CCoFoBdHnbYqozwT54gMknlSENUJN6UG8shatV2CFqAIId+Uz1uWwXXb9cK2cMzAnoszeghi/+RKgZWk6Bxt+5KiRvgrJQ+Aw9VpstQxFrLhf2N+a770iVgZGBNtD18+QS6QynQJ48t1KjgpIxWxHtRVtDWcibX55TS1axXpPvNe7PP5AriHXyd6vLQjpJdMDNFDTcQwJ/M14qLpabs6Z1Fq62WeIMd3DzGfglVRhCErs92es32FiBkYivsMfyEnd3FLLJ/kGYuOkXLwQtKvLS6faL8UfpIIkgYVFUmD
    postgresql-user: AgCowAAJOnv/nXd9H16VWoQhVzCOE6PgAFPJRAOdHXjOTuD64c4y1b4+OfFyLeITTpK9mYRWegPh9XyupJyBEO516un04ZEAiW5Z50csJ5V4HElERW3DusKEyJc8jsv+gidfaDbBfluUt3IT5iqndGgQTBJIzpsRkcxAbEpOZXTEk4oBBefG1p2Gg4+jAaD/xjpRNXsK8i5+vKnGFTn+nhNdk3NQtfggMeKO+DP8S5gjn174jO8uv9wBuH8WafSb33ClRIM3HFIzevR+1RTmHWntCNDKAbyIlwuuwmnKEmQSGRrWC4hmMlPE2Sgt38ChPPmsHqSsL6CqjLNgKOQUTg1w8CmtMEkDaK1NcLq/iz4VQePT1aAMtMLh1jbzyimsK63phxfxZ+V0i2g0IWkdNoczwQ+tL0V4gHJ96W3zWmMIiDnsIcxtLqadxmkhuBisZ1kdQv6fAOafLOVIF0ZCdKAmpatIqkfMFCy2/KvPgPocoosbQgADbWvmuEBX7QDplNjX7+HUQEgZCuCIWEQAdxwdlqg9jMOLrSmrTO/Ix7PvpLWGiXIFjRmbcGZarHI6F/XWVoEw+24KFL/vdOAs/fwcjXsQB4/g/vzs42zyKU15EM9K8/PShqr3+3L7nNZGZBxFL3DPJn2bCvy1jNkwQSTN2tMo6Kj33cYrkIt5Pd1BGc7Vg0HfbUDIwdoTjGCOQVVRZnb/6wIo+OHF
  template:
    metadata:
      name: lakekeeper-pg
      namespace: lakekeeper
