---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgresql-secret
  namespace: dagster
spec:
  encryptedData:
    postgresql-password: AgAKb1qutjAZndhkn35W25BX1oCTlMDvrBRg5XRUJclDmSYrcvd2vQK3+brUgd5YZWz6s8fXQJAmiV9W/ONl++RirMPIINIPiHuHkHySEyWu3M6yl4L90WdvLOz3y0zH5Ckg+f1CRcUU5OJHnaEtuZi2rey/x+iG7BZx/SzPm9/jY4TCakfOzknAPcxLuDLFePcPNQu0ap6bHWZNMFk1MZhSODvW50dqZQr5KxWX+A9vhq8GfKo80Zl3qKLiTlsPp9XOkvYp4Jkjl120hkXsuErCFB4HL7o6TDURG5A/mCFVGOjEYRGCfRLSfWynFXMUkY5MaWRyZQ2PPR0h+fDJwtmsmZrkLe+LJ4k1Niwy/58jgrtNIuL9s3nmvclrag4QMoyWEn1Ii9S4OEGLU4k+TFlGEqVserh/LW4asxZBvtY61oVc0Itjn1BSP761CTaAEFKCJs7QNb8Ifk48chqK3cE5QuiPy0UvOg4XOa89Yq1mBU04BXwJ43+kUm0ikork0XNNlSoWfQx6zKFP2jui8A/e53waNqiuzAYoqZounLCy9G9ltXOceQVQiXAN25Hj9EuKunCbYPDSYnPwEgO+ZQ+iW3hmor6Smq0GpNS6fhl5wZawjer12wAqLr+GV/2Ii/IKOejQvM017EIsTzH7L0NEDdXcEx04PG9VT6MkfJjr2CZxmiy9J0OZzSTTB8H/lpECE0hFBt5tMwHLjEMcEdJm3kT/rKF53knAyuaV5sK+bE4mM016gv9up6X9
  template:
    metadata:
      name: dagster-postgresql-secret
      namespace: dagster
