---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-api-keys
  namespace: dagster
spec:
  encryptedData:
    CRYPTOQUANT_API_KEY: AgBAvq/ukr/OI3f5uAkCHLPIDDlehasxT2qIcidMsiAaZyIa3lQTINP0r+hoPNbTv/o3NwWAZxQTUFpwSAecQhPlImRztlTwevQ+6TWLiU93E5lgee5M5bn+mukiKdxQxk6AhFLOOmh9CEFG0pbtd7O8Qiz5usEi3kYFEtL2UbHxuxQGYExI95elBOICTax9N6uwBWpzZefOSmRt56kJJEAXxnttzr44vxyp09B2xYnmz9HQE4q/s6xDrOOWbANTQUvQR/7EH+Jdfw6bDeaxM66pF0bVT0LNzVuMABLp4BKug5nx9QKU8AdSX21qS1Phway58pnqKBOLLgc6Iw+Ydlih1ifgSvqmboPxaIVCJN3tpWcpYbETCUhl9fxDvZxgDDDUExfnjRUSyN/TNWOjjP88cDq2OZq2LdFFan/KHWt7UoXCOPQIDMtsLQhpISeeMbKezlFaGsAyCZ4CEQV2U5oIzDeWYeDJWoiJpMDTNQVH9RJNHJ+ye2yiVaxJ4PKMrVZwS+xf47zP5SJocXM274NNMK/be6NatUPNjqRAN304xPFK/q9eSAbLJIZFHQvOX6Myor0CMCkB1L9wqs1acTWnPoBKnpgWdMiIYfgVA7C48uk4gh2GX2PLnGtZZtKdcDoSuF3GeEwdW/xNZ1jADRXECBDRnLcupHj2YcWhBdBdPbOJqbNuCxxGkBsF0h2VFZPB35xK3jEZmYtpN4DleZTQR3SbG+BHH3ML8nGiCqEc0pANHxIiP0IN2ICWgVVXXw7jaA==
    FRED_API_KEY: AgAgkgBEAC90B8KPSFrKbGh+VsAk1BOFq0M1QojfDNJDr57W4CH3XFGVrCchpz+RgrR/fV784KOxO1N+iwryKkYObEewkNCscMgX0ECoc0oHduh1mplcwglFhlNhRWeqDUsYiKJmgqSmtllT08ppH2QhaX+qmPlrczAbliB6mX70d343BeppAGbf+ZjgYUX0g2fLl8FR/H28OcHdgy9tyQb4aKXHsFmR/T6zhz0/HMtReXjmXU6+04LjDxKwjHH241fX6DZEmmXs0Y8EjZOen7jhu/s39GEuFDqhW/yzf7Xc1xAo37AeyHlomSkpBq5n4z5PCGIx4CAYRqXFPh1JY8mtuu5eW6zNZs/WVsVsFJXecIqTESVeXnHnmPj0cYMMMXnRgJVkhLL5faDAFUFwkJkrAIKgwroKlaXo+eiEp+bXD1yCvCnkNZ3hlNjcMPmo8YlhZ15QFiEtBV7ELb6CM5i1zrjsr6kKsUQIh24UizyBkjGNVsAcPdKnAxJ50G9A5SA6WDAOAlHSJH4D9pw5zTyQMGP6gN6D7NbECVEG+Xw/1oQLE8On9bbMA19W6BtrORptkFhyYa8lmJ6Ca29/rhRNi1M09NOf9f1MP8EirsPR+TFn2+H0VJWPyz955ziyK9AEElUWGb0QHfms54QJ/eoaoD7K1u6j3BUfT2KMPFh2Xf/7bXCy2l6ImAMuhkREjV9zzcqQjwfOMk4BDB681uafdsMWUL7UC6mXw7dAtu6w1w==
  template:
    metadata:
      name: dagster-api-keys
      namespace: dagster
