---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgresql-secret
  namespace: dagster
spec:
  encryptedData:
    postgresql-password: AgAR0AJIPxmv65ehkTSNsXQOIEgJq63l3kt1+q8K59cY/Sxka9LxuXUKxGKuR+Dgvsh1JqqEBagb6H5cvlnDM+1D8aBCOUw3qq9y0IpBEe6ezZNryc7jeupMmIcpi9KdSX6aPR++cVAt/h+azhJY4F5cxHglsvYFMWiFgrssLXRsx8f4/8zSDvCiOPvp5loLVi/5NKe3RxBOTE+OyN3IexQlJw/BsiBoiTol6sr1hij/ensGf4L8V01uOW8CNjPFDIriQnQgldltsk6ImcgP5wCX/MwH6/OC6hZGxipuRn3AtCJOUx2OYlVsbxjArf/Swlv6lUg59jIBwVhCbMxW+dp3wlilbib4QsTUff53M3X4iBQpNDqh/OcAzLvLQmJNmdYXqzCZHSA7txIaXVE3PvGHKuFXcRZHYAXIhCPBWa+Yygnl2kfmvaHE0MqO75pWhdI120BCuq1cCdrCwxWUPggkexfiVa+uD72p3T639Ul4/qv/9vrMOVmoPo43U2T+ar6am2NOCueDQZkQhkihUHR+hLB7P1I8zuo+enOV/bNoCdTpTwWlxjielWjxqC2NhWLroFb72foSnC9QRk9MubUyUrRWjrQm8+80UPRyjJkKBgvEe7Lusk8abQjxaD41sI/UBYKzH+5uLXdEPkDJ7Kvn0O86/aH/KTfqNegQtGeoNXdaqSlZZafxyptabBlZeuK5nvLZ0b88oUJ36LfDxWpJutg0d/rkUs/AYW6xQXQPww==
  template:
    metadata:
      name: dagster-postgresql-secret
      namespace: dagster
