---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgresql-secret
  namespace: dagster
spec:
  encryptedData:
    postgresql-password: AgBAyea2iUwK8fm/Dfu9taHFAlgU1baEnN4S3p3QdOVpDPHeBJ7AR6hEnpOpC1ErkwslrAL/3s7DjWjP18ytoDwQn0Utzx3rmQsygWZ7yeFBrsRvmQPqAgo700atrZNY+e1RxlJWkbu8qWVIc89rOMqQlA880D4lSB1NqxwnxE+2b4Od/26J7PNo2fL/HxmwaFk5ViERXlT5NBKdUmJ70DvoEHUCgUg5+4IOBw5VegAKpbmzgUrXeDRIHw29zuI0/8Fsh+pNTTZgnkJVdyO1v6m3EfbAlOBYygHUGNqAsapx4G3FMs4pu++fcPsVH0UZz5OYRnw2nxo7sGm9gWSRRkAikOCq3PYkNjjjWffN9yDaxYSKseG1t2oT+eoZVH+3Tvt9G0swYwF1ntXdpeAPvTI8Pr7HT+C1YO7eXLs/HuypLb6D1rDYH2GTAA1/r2PhUIuLhXVEjYmpHi075AXKbEGXXYpI41fwSeBdx00Ea66nnqr8WTWSbudCDh//pFE5wzfipntL/tIlEKVjQKh1xaMwHrLhXY7Re8Cyh3vzftMmikqbVf9WuzQsce86Kz+9No1+PDkZCKtGNO/mdHsRL57VaFBWHTTUMXB8MgeaanH0tGYDeQiFRCGN/DQM7JG7cKmZadzj7twIZr01FtgLdBR7cL7tZJ4D8muk4xrO24u68ps1RMYwWhea3byU+9ffxIhD0kCvf14vpfiXaumhn2Zz5d68o2ACQvJoGXb2v9wVKyP2Dj8YLm6KpHPy
  template:
    metadata:
      name: dagster-postgresql-secret
      namespace: dagster
