apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-secret-reader
  namespace: postgresql
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["dagster-cnpg-role", "iceberg-cnpg-role"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-secret-reader
  namespace: postgresql
subjects:
  - kind: ServiceAccount
    name: postgresql
    namespace: postgresql
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cnpg-secret-reader
