---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakekeeper-cnpg-role
  namespace: postgresql
spec:
  encryptedData:
    password: AgBHiB62PqnO31fah2snkUJkPMjSwMqDrK4drymGo/eODlYgDBFLCZpY8K9FAKm8F9g5uqWRH5pTm30zvI++/6/B2eXeyNAKP1MAgk1RT8AKjuQOt4VYlVNLcXsLvO92kVjPpuPH0EMULWTZ0RYK85MLVYiV2yGzJbhbe7TTwKXFrmRo5H2ryZ5ZmA+8DrR+J+Wq3gDNKRxDPh+13BeDYmS0+DqaLYY7LT4SupZDqVjHkGn0wyP3fZVOmbKbuoU0bGpLlSWSkPhHPsGBK7JX+FLKUvhJz16+H2KZY+fFV3Mht1rbL875doLH2y0iOgS6TYSwo3zK9wHV5pJT4W2+xHebEq6arIWwaWkUfwplRFrgZMEUoF4QQW5DiqUSt89ZDlxQNgrOIiVrNBV6OCZSEGtG+b8asCWuWOi/YC7iFIjzQX3fY8JddLTvwrBCi5SUEAzPM4bM/ZYnTWw2XkjqcY91iExAT9sWmxkis5I+gFit2GYrlWvtVGMC3S+OG2o/XG2yPO6NtYwa+RQIFao69wF91xdgUzgiqq9Mo7sTF1YZ2n9PoFgX87GF4s1ubxt/XVaeJr+GujtKsmFRmegrM+L9Ssy+NnTwtmq2E7dWZoyZzhpx1BZh23rqUXFrM0KO2Xz2BjH0ES8ZpK6wFQYw5AZ/JAFynZs58CA7ygLtYeLS3ZIk+xUtiGGeQ1nRqnXKXe0t/WVPtSJ7UqDpyWIQLbXBNQN6tk8n4RNAgXmtd8tiZlRRuld2IxegV/Bo
    username: AgCMdxLzua8ismXOTkeiuVRfVUbpEVTciWC4RSZ2uwwYAaWu+8MEiB9vgCEN1cSXoCe0E7naopSeP3c//5ESz9smKdv2fm1Iz8ZvEw/eQVQjD7ig/bS+WLoSd30TkDh8nnfvvosDT9TGa788BgymfrImf80TD12qA2D8WdBrvKRyegAp9Rueni28eibhPM+1oszQEm7DygIAS2i27QQpTElzxhYZF+EUbD8LzIxWk3yqe2gG7DApMSXxoJ1xhsp/Xc/p+yM+fqx4+c8td+N9cnfCH6MKKHvDS/kCxBre+7FbOn81fZ9rqtuH9hWZxBTyv23sF2BBnwqleL5YFt8mweKs96JhuyFGl+1u5NVLFaRBzsVER6ZvBItdVrM7yJMp8TIxMIJgWmH5FlGqnPExmYYz/lZfp9Wpb0skSEZLKQdTR7U9mhdxPBNbd0CXeziH6lZy8+JeeOJhIlbp09r8AwQVrm0tSNA/RLErXXfR8ZpYToa8xkI/I3j7KiRZzRj8oFBCu+rbvaf3jsGRcAyAmqSABQ9YsPNMvqbfia2ZjYZzFdIDuKkBkbKHy3k+Rlg/1rVUyvgz2GZfsMbyjm/2jB4d9+O4cg79jR4bjNtB7ElzSH6spNfA5uO56WRkgb4egLgq1vThDHsyJlWN5mqnpomA2r8OOZEn5lhciFtz3Xq25BGznYU5gMhHZD7IrT2Fz7ei6zYQkQE3LvzV
  template:
    metadata:
      name: lakekeeper-cnpg-role
      namespace: postgresql
