---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: iceberg-cnpg-role
  namespace: postgresql
spec:
  encryptedData:
    password: AgCdxlNpcgMEW0/PwrfswvZjnvQGeR4hJQyhJWXWnFpyxYlhmZASskfeI9nZL+pf31rrXx+lGJqnFc7TWdHSvFXUmBqpB4yWlufq4VyW0106yNKib+JzUgL76/yhEx+05n3TnGoicIp6vPUXA1gdhD2049ethR7rKEq5rDrVf3yGQYIbNA9035tNgtw5uiWR4c8eLMwFA4B0a+olJcjOvhEhv6zpFSG6o9haWtORy+POQ84ef1gv3q9/TU5PJxcriiDGgkN6Dp5aO8zC8425m3P5jsAGLi4JSYdpHWBY+U1I9+Sr1E1Rik7E9tVTTaoBUIbUkWPsYaIk4B1Zlk9zPimbSfxBSfJJQyIABgCY++S+tFW3WUJy50fqzvCdjzFPtHUaWodETDbjzfB3EOnhucEBbt1l3y8/eCvCWE1fWpk6YsrU5WGuJyllwg7MwXWE/vsRMKOFsFsfR8hIXh0pDn3iBT8z7aKl4JwYUcqupvx1sODsm34opb0a5ER6f7AZIwM7952MrdNZEJHSKFFCIRWHJUBvEwDRxFe8A/5nmjqMG9eExjBiMmo4ZAeVn0trNxdmjHMbL9ft8DwoHCIpM1rZuUMR0URAIwwxyvnA6DX52TNHSPQ9TJxYCjn8nrggDARv0MQLyNIuOHUMdbv826Iy6xlH72E/nPALA0Xn1UW19KYfo+Kml6bWAkSxrJnD8YSf+r2BMcOfL30t+qu4gUi00iFtZead5VZkhCBWnfVTJGtKSWhmsi7nSdhl
    username: AgBvnzEyQEyFQmD+nuBvR0JeiZkx6/to0SY6Xnqn700lJQkOFkTvApdKml2G2Sijq2OYHHmVNhnU+LBQyCvRDYGHpwWzAQxKgzSJLTEcq/CiM3RRFVz3iHWlQA1RHOetocj9XuvdrBvt1uw7hK4xNUjwO4ffavwYlc5ASBGL0DXsCckPp8QSSigXBgTm9ekXEJybppeVBkR5C+g8lCyeHmSBIu3gy86Afki8coRSn5rXriO1jGbjOEecIaH0CCUbRvZOzAJtT9wm8AEMu13m4qm7DGaSwKylwH0HJ66B6wSxu4I8w+Z1OlIsOdkPzSUVZXXiP8rxNn5RXjzu2aL/1QfuNd4Wh70q85MWUwtxdMHUNCjpwJudUqladdZccETy1WZ7HaoUvOJgvvSgWVAWRjWc3wodrAvYMQCvwrUUpLR/qSJdj9p2ZUwIAUQWTwPSICVsQ4So51nB/cyUNabiQMDxaXaxV1esN+mbzUQbjBb9+Y9wnJG+hJ1eZ+CFuj61Az8ajgyG7QXuIKFyyrkwGLkwCSdQun6bSWjXjA99Unj4GBHik6aTIEOM5rbNweUPIOtHRpXVdLitPPBAKIXs30tFoeA9n5oYYXBJv0JR740WThYn1pDsS7ttTrtr+8X8jWX+y948X1ZXhS/1fuewB0BWEH3w5VrR10M0jnlpJNekaKJ7ZVgCoZ8YanE5u8CL5g4k/zAn5DDA
  template:
    metadata:
      name: iceberg-cnpg-role
      namespace: postgresql
