---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-cnpg-role
  namespace: postgresql
spec:
  encryptedData:
    password: AgBBO72gJ2EPjX9DbTY+nNrfDBGt/H2EmBOr083XAAuKCCxaK8M0NtVeUYW+0SLVRbg6E7igNd2bxpmmhaAKznvhaAD5YFcr9yFO+Dw0qjmQNvyS7HnAZJDPJY474nCpFror/jXfcCPiLHbTebN8+xM1pXDgYBb6zdNyHz+g7JEBz73hCbBKhxa+8b2+dkcwp2det5zAyMG56bWN/Yad9emyqhLRLd002pKv4fMZROBUA8Yyr89CvJrnT+JP1NXJsN8yqVSIhndzP/fgMXt/yk6QS4tkR1Sf1gT5Yu+ek1CeXcYEADLMO5A7dYjRjnHVL70d6/rC9pR48zosolKAa0xqbMbIJghvGP+QjJzIUeIDopULuTNc39HqFn2/5/qhUAb/0E7ospqUpKW9vRkT8n2FyWF7YaSamzKMgDDdCUDugjz6U4jbDfrxnCdXZ3WZXUFF2tw8IBujrxQLU+byLHicrsRY5QSAo38fSgGKYnENaETPhGFg9dLiNm+v8ED+c1guIXPzzyoTSClzs3J11ARouwWjFbtJvpGbny4yIQe1R0sGiSNU/3e51s6XLeKMHveibphryDhICoCaFzGFV3jt5R++f5N3QAeyU99kqrSKphL53we449+Dq0JBG7qWblq/6BA5PmG8Dl2m2mvjyERMxvbuviJbs/Jw66n7DorB3jWdLFIfNwbt69cStbkdDxpvoPm0Lj0NpGZIFxMVIsnS3SCjL25TVh99v92f2NdLsQ==
    username: AgBmTs0R/0AhkwMR3oAw+9k8b7y7W/8i4Nsv+MO1fLIcX8DALdpe1ZjKtR1mWbM4WGdvOaLNadn/OdycmEbNvNjU4Wo1w9R+hwical0wOd5eaIx5M5vHE+eEQtfrocvhL3C8K6EOs3Q6D1XW80iShACvs3X9x5ORINmEAGXfp12u+U7ZY+eQ6xJoemuIjhyjWfiNIIf8BLd7D95pTWNejiVV2eb9UB+CnRgtYqO9RGxaZOxAvr9iyja2m+R1RF7XMzpxHTfoDj81q9Ol7jwgdwK4r1M1Gepip12n2DqMI5gd/lqRxq5+WXub5/kCBFcfDaNyC/Z1W9IIjv2/js44ACeYEqkPAZjx7ukmIeL3QaxCT/ZwgaJqS65BvlN8TZL/7P99kK2G0UwG0PR/FauBrsyHU7Sln672I/qtWfnhGslaZdnvOznRDpk1cMuYIafnMglZpZD+AOptzv02LoeClXk9n3wDfhQu/KG6N0JdwjEAKX5MxHb8rJnp1F4msrjc6FGvUWR5VOtod1dxu0KwS3FDweGCoiPTWWQ0CgRe5hvRI3n7jv2pb1dOrTleqyLVIMGilFPNkVLgOATcIZ8Qqfn6W9O0T/UwvMf1AQacx/lB+/wKmnNb5ldqJY8B5kPhYJt46jtVK9TLuDSFo1Ej8Tcj5Ijg+JI19TH0sLJyJGqIPCP9I2ZJWUrQ+e4BvaXtb828vfC7m/2R
  template:
    metadata:
      name: dagster-cnpg-role
      namespace: postgresql
