---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openfga-cnpg-role
  namespace: postgresql
spec:
  encryptedData:
    password: AgCZhhR9zAzVrhP3vJjLNB3jJxyyGuBSSmZrzR2eJ+pXLCmVeyTAXbAnsaY+6YnTOQ0oF0KK46Ux6HdnTXGYR250HG8OvH34PnVoLWO+EPpQCfmzf1Oo9fTS1VPk4KWVSm7Pc2Wyp00rON6TgDJ4igR5lnvD2nKlJ+Yd5jOOVA7DXgb531mNFJyt+tmkcA/nSMTBiPRQfdIqfHPC+fv2UOiXbxLutlWeoih1V+pwwtl78QSv7SRTszrosyN/YNzvw/OtJ45+kmzGXHiVrfPK5HTe4qpOzvwXfcRMyh8+nuCxjJ49dsynvAYKP0MDM1G5QWuI3Ez57uSKiYsOr/DOtA94JmaPkgUIZggSXl+1T3d6UI7fp7H0UARYGBiw659GufcDVSb3KdTTQ+Y3kCpHivlxKjdDuHEjMWEppYylviwfZ/2Y10NlSEIlPXQmhVehAgQE4u4Atp4eZ5iXJtVN2tdj4ImXSpIjNibh9WQfzXFl8xLjjBY96uvUvXO9iFY1HLwywM3bApZiGpQfEbgfIJq93vk9gjj/fH6xGVWQMgEptdInBbiOGNiJWaODChpILDSE+7pTghdlO9Z63wUajTPKaXsa4leTEpxwYLY1yf/Af3XPug8wCeDzMM5yV4qK6g2XezVN+M3G5I3Gh+5IRYoKtpgsoY1hcvbPUoWEUM/UZYM0LSuIjt8UQTnICMHMOuVTpbsnr/G8/Y8FCJx9AGRE8QYFSrh1l5HAA9m9fazK9X6bmGhK28h/43ya
    username: AgAYhFgR90qL8adqZyZPBj8rPFGGbErdhb7pAHHV+QX8ijcGnGIG/W6mRSD3qjy49IKPLQ8Fz2qY5E204QL8FUvqyq4VDU6wbimu7viCOMWc9Do5ABudrsqalIc49QwpiJx/PYfsDxvGE2tHgMunv0JN/u35eBCu4D1vuoENqp3jWKLfemzdPrVeYhDoqm6vxHlu6iAq3X7mhOt5lL27MWP9bfWX1HU2LyNHCOgwzrI2R2N/qrKoOcoQ30ZGFevcDSdRYT9I8V+WLsXs+wQhlibLiO+RqGu5dxbGmgSvLG71wXF+i1hSSaDi9oyNwrWBPRSLamyaEDI9Iw6sSGZRighwDtgYHlzFvQ1sXCK/tj36fKjrJ68rCJixtPsbpZSd5cRWCvb2exBjAWp/2vszEZ5ffG9pd9AY0A10JHxVHrgSgrcp2g5+xI51/5vpqn6pZhdaodCp92XNho3rOl0eAlFAeNe+0aiRq6DIeuHILTHPbpPiSIncxTkh/KTh+h6KGy/AEUx/J3bvKeXu4uGsacUPOVoNestPfifZdzVQu0sdoPpgaplli4ot4wqNRsjfSzp2hk9NOM6j2PIuORqV1k+DMn8D5e9FJLNCD26Dq/OrQvIzyM4gwhxpMPF6ILa8N3jUMr25tkGjlCOIAe+JlRo1C2wdTZtJQhRtvCAKjZjbvPWZRxaU+vFwgs5TtivTpFqvpDr9Y2zT
  template:
    metadata:
      name: openfga-cnpg-role
      namespace: postgresql
