---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-cnpg-role
  namespace: postgresql
spec:
  encryptedData:
    password: AgBD9YwR0UTkxQzqNRO7ZZTUnUhcLluQnvIMpg2a6+VmexbovVuvXZKWHyVDrLU0EfSO2PCI+7vFs1MQLEEG2fPUBfVVeE/5/+jzRfMp5tlZ+dzN+uWENBkDH9iI33qJGz7oOU76ocPp1cZttOYw8TE77TsFypuUbJGZuWLh43W/52+cL+dB1+nrkAmXgfQqqgx9O1SAclG1P012mTPhl6csWJVPlWDSF4TOvQttnO2a6A2swPwgQl6B7i5Nl49WnbxGEA4TskT/cLAdPY7b7YHe+2JI3UozyMyVVBfbQtV0haSbMvTEVQ2rZqb6xKU5GYuk8gzXsyHD6W5RolXfOrnoMpKEhy+380fLSdkRwRLODwRFjnmrzU3xJQCT2wGGIr0/qrU1e09qrBjx+LpCqyRtqahc3toFk4Nh+oHkCuGZp4fhVw8s+Pe3Fi9in/CMNv4oPA2EYBqPxPop/CjsWnIb9eb4ngB93Odn7Q1ptTyuMX6xUOrCrUY+tk+nHXyBTsRitl+YiPRAR0uoGcHkUXfoyfutK/poE5dcgI1zCDpnkejEDZORM3qDI0l/R36b9SEJHzwL/TaVuf/SLBnbKgqCAts8XHO3sCqg9LcNniAWkabs11YgGLtoWOtxFuFLShG5gW6Voe8rap4s01cYttyirv0i44bGYl+We2EvEIQAxbF8kHcGth7kEx+LpmrjNmFekFqyn4SpwMRFgz/MBQxnBdslyCybjH4iuV+gkRE5ySy23aR2qkydUrYo
    username: AgAcH8IcqG8VsEyBq6o1x5BBWMOaUbKRj0iurFpcgAQxeRtbxu0mJmW13C+udYVuz6FanJdtPWH0P3/hakVyr/vLQV2Ue4G3Jy5H8rKdx3yYA0ok5KbLmrXVTYDWl4o04zG3eYaxSDR/cwkAhbmT/PVx1J8QacGSoZzytxiJQYlOqvRIkD9kLZ2Wd6mPSyHcvOi8TTSnqs3sB7Mq/ZSC/vO4ex/sE5tEzXSwp5aOekbPeOFcNNA6SPfwoDrr8gI/tdXY/bt9QWC6XSY3WsRvJvNoxxUjec2ZoRHtyJW7/Z82LnRgxtjqWWg4NIP9x10v3WMw2Pi+UC4oozEEsC0DtjXOGzff5rUdFY27674GPt+iNvCiY7A3LHDwIgMfv7xzSFdt/g9GWyrJSPyoETssreeB5+h+4fZrYuDFrPps3qaCERab8vjgx7tLPKZM7qBG8/8J/dMTKCFFRUiHLplDsslHskGUqbCwQmhAOdvu4EV1TPbw6MjFPnt8OgH2p1XtaxZyEVN4dhEOGcs+uQRnEHaYyBiPtANnq0RxuGboomK4YsUETrMMW4MeV1QJnWBanbyX9f31f+oIqKPf8lTmaNTyozxlVJ4BhJJVPjc/950lJb2gwWvqudIXx8SXhf/mfWCJZorBM6ZQpj7y/2wZ8YAkydFdlmavHhuCYSUaxhdS3nVLV4Ftkf5Y435+JUAh+d7Mmisgde3S
  template:
    metadata:
      name: dagster-cnpg-role
      namespace: postgresql
