apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-data
provisioner: rancher.io/local-path-data
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
