dns:
    domain: int.edgedatalab.com
k3s:
    ingress_http_port: 80
    ingress_https_port: 443
    ingress_ips:
        - 10.0.0.10
        - 10.0.0.11
        - 10.0.0.12
lxc:
    ansible_ssh_private_key: ENC[AES256_GCM,data:9hzsd1LTfqDrUoWL2Ik7gRNxrw4VEJM+pGx3nrvoRlr52b6kKY53L7tJBJdDXEVpsjFZbeWDzPLZG02V8SV57tY63QMsJLYpGD1bqURrojqvX26o/gbtPD62jojYfcAUEUVD5hy8C7nyYVrGg0AAxVngT3qWF7uxaXhmkPPN819N1NPvHYbKoUBRdv/c0eYSMLIZhBK0+fMzuBReLCKzvirOTFGYATzqcBAEO9BtnNVc4N2imTpMFyCOOf5bkyGml2w0BmQ4N5bj26L7DZrJFu7Y9vs+JqQ3n4Lt5XyAwoNJ5RzORNv9pjjDJrFGG1T49neerCEnYMrnZflZMC/heWzkP0REIPHqg9TbdAeswgvd32M3W0GjbFST1Xev5E/r8DZMcldfqvxafs7kh0f+rOIiNLF8KMjEgcwxIL4C4UB/S/5Upc23cE72ESk1l9Z2TB99WeDtgmBSygqlQpveOOcqDGFKcFFvjouPGI6SCkVGmWcIRz8+FIGy427g+Fo1+pchz5lPcD2i/r7axhcVqdcM6JhJBYiEZDsHfM6kcGbAEdojDm8m9DNgb/HSx+I5DYTrmt1DUz6qPxSPnQqwJB6JMWCZk5EIct2h44Kg2c2foFlTXtzttyCO5ySlJTs9KIAI3R6/y0sB53XE7YfjUITbtPwqe3IG028lRVuxvPaUcaN1zodxSBHsyed+DHSQZD4+k/ojo5OAeRnwCrUIGNOYnDE=,iv:2l+Mc7P2ad7/ewV6mbnIqf4qd7aWoiqt2wRNXs92QzQ=,tag:3TEACSax4ufRFgbn85bngA==,type:str]
    bridge: vmbr10
    cpus: 1
    disk_size: 4
    gateway: 10.0.0.1
    hostname: edge-gateway
    ip: 10.0.0.200/24
    memory: 512
    ssh_public_key: REDACTED_SSH_PUBKEY
    ssh_user: root
    storage: local-lvm
    vmid: 200
nginx:
    public_whitelist: []
proxmox:
    api_token: ENC[AES256_GCM,data:/JtuV0oKJoRaQrFFMPznW6krnSXRO+2VzFOS1cX+os/BBvgn6vl4Rf8FrF7XGVwP9lHXBsPWjHhUKlrJPw9lU5D9,iv:uengEtj/6Q+XvrQiVdGTSXiuPrHloxqzIOls9KWSlbU=,tag:Ik+HZOSndway9HLRWgNvJQ==,type:str]
    endpoint: https://REDACTED_PVE_IP:8006/
    insecure: true
    node: pve01
    ssh_private_key: ENC[AES256_GCM,data:4idgdILR0NoEgmLf6LeWb6Y0Kx2P0NgNHE/8bxBqNG4Ecomcgffnd4Vh/64cj8Yo6lv01iN6fQg/xcRvW+RmC062EUHKoVXclRbnaZdwpvqO0eqP26fk2Tke9H6wN3RMnJWTvuDCS0J7s/k8S6QkQ0PReaGhQ9w+i0faRXySMiMf/9VqvWQ5Daha3fLsFgrPxtqrMoxZ3kFJLlXkqe5uFDRkoA683++IY4igSiE2Db4d6pU1MBESQen5dYBWodKpcqbEm8atMKegSE5cXhBoT/6pZVepmITI9XI5uLkeK6gCjGR394Hfrr2MIs7S6tM1/pxhZcSpnwfnkkA5Rc+PiTZbFx+vyYT9AWUkC9+kTBXFwCk56UC4Sv/McOMzbHkUyVIOuWM1Sm+X7SmH6Ndcz0pmNTof6g1Klgnc98V9W2Liy8tA5RxzJJIyFG84ywvOtNSGIja+tGlITq0m5dc5BuYZY0HympVRYbpvS/YRZFwzFXstKgYji6Wnti986MOTp9AFKSHJTFCCCy0nbm2pPFwweAMv/l5DRaihtvHLbAK0r0qo6nYf/Q9TGsp1QjRZc5KIlclYNvh5Pj/XZNydq/t4bNt9mNl9DyGnxcoNr6IHU0yUy5q9hTYcUnzXzj7fyLvmxdqanj7041YHgQTgZ9ubCqIuA9XEkFlAmT41hMy/7Dn8ZQNFpHErKCpvX1tjfHpcsw==,iv:Q0rLAliTgvh/UEy2M/nKcKuEjzQ05yDTopaiHW91HK4=,tag:xySrrkCu1o8P2gqcxKndvw==,type:str]
    ssh_user: ansible
vps:
    public_ip: REDACTED_VPS_IP
    ssh_private_key: ENC[AES256_GCM,data:dO92o4M3Jhuu2hjOzqrvR9qevXcv+RozwQuQx6Ph1JDwkQ++cO8wWul92jNnxjYpitRedWHaruVsGgbJf+GBx9N4qrCRL9jvEBiH3tjQVszZiWxAsFNpW3aUROBdKmYsLBVZyyO+dOrrr6gCefoKeJLTJEYV09kaqfW1Jj9stRA6H2/nr0vTzPzEfdmBN9Phx1fBx0qZUXAFrpf9KatTXbKP/h4PiLAOXpE5Adzaqa08Nk5uZtj1qI4CpLdGXgwXkP01OGOqNKiXHJ11tr/5qlaD7yRVQ1p1+OXSUxG9GnUvxKtnvLzt10Zf1Q3laJkO5/J/7LoB8ITOg2cN1oPp7qEgkA4gB3hsrtEC5sr43Coip+4TENUmKa/GK8Vl0Kgw9tPbn8zfH9zmzuMXLyic6ZHxtOozD/hCD/w2qejXo4a7I7nzZ4KEbTvnH4aV/dvTTGitYih8Ym1R4D9BRxu6uXow6FOcqyHlAqJ9JkANk1v+7w6vvl10jZvyFANNDmSnNVVeWINygMEF2PRaaZfmRADHAwkjH/IrygP6dS2UCtTjCMXNeTD35Z6PJyvYDHL/OKfibTh/Rh5Tlh4eb/QUcr7F/K2YBUyft3FXj5R5rfssKOs9XjLb14cL6q4lkZ0o8xQLwh1TMv+uwAGJ8IZ8rlEsZNx2R5a3YQOzFs7CMXXRpQgWdNLLAFy8IlC14WapcgoahMBc8/7KVDxxctyZIW2OUIc=,iv:Z5IJBT41MuEE37VUbrFK5a/Qh7b+Ki1iDRzluZEo/3o=,tag:UqxjIdgNYXuW/YlatW1Ucw==,type:str]
    ssh_user: ansible
wireguard:
    extra_peers:
        - name: pc
          persistent_keepalive: 25
          preshared_key: REDACTED_WG_PSK
          public_key: REDACTED_WG_PUBKEY
          wg_ip: 172.16.0.10
        - name: phone
          persistent_keepalive: 25
          preshared_key: REDACTED_WG_PSK
          public_key: REDACTED_WG_PUBKEY
          wg_ip: 172.16.0.11
    lxc_ip: 172.16.0.2
    lxc_pubkey: REDACTED_WG_PUBKEY
    network: 172.16.0.0/24
    port: 51820
    psk_lxc: REDACTED_WG_PSK
    routed_subnets:
        - 10.0.0.0/24
        - REDACTED_PVE_IP/32
    vps_ip: 172.16.0.1
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aswdstmpfeyztl2z0mz7a336g2kxd9z4g3zje3tuf6lqzum3ravs0d42fd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dGQxV3pZYy9ndkd0TEtL
            dHNJL3psOWd4a24ydzR4R2l4cmZScTRXKzFrCklpQU9CRkJiSHh3dkI3WXpjUVYw
            VEhWYWEvWGd5cmU1dVFKZGVNMDRaNmMKLS0tIDhuaG1WU2N5MmZ4SThCWUM5d05C
            NG55dmg5WUNJL0k4WG0rQklRWUtkbWMKA5hTgVcd+eI/fp66+xiSXxP0xjXmJZB1
            0/meeTljoS5g9m05IaHkWO+i4sQ/D9gM3ais2U3MBxOWZD5ur5jBQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T12:52:21Z"
    mac: ENC[AES256_GCM,data:MBmAB6nOr3neR8U5b8n7opk7TG9E13tFbNWy8YtuZ3sbctIHlvSXcV7Pc5CzCythbV44HCZ27geVt1W2bR8ndmTnN1DTpIwx/3NBmhKpdA6v2ljI0dAdnGNCDoUEcEmg4xFCnnWKKlebPPhZS9fg48eY+vnJP2ScCKzntEHNi84=,iv:urItr90sG3EdcfLaOXr4IEYZiq6TtTrOlbQxi1AoqQw=,tag:CxzpEvIu5lf3aU2zTUcfng==,type:str]
    pgp: []
    encrypted_regex: ^(.*_token|.*_password|.*_hash|.*_private_key)$
    version: 3.9.0
