apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure-platform.yaml
  - infrastructure-authelia.yaml
  - infrastructure-monitoring.yaml
  - infrastructure-postgresql.yaml
  - infrastructure-rustfs.yaml
  - infrastructure-dagster.yaml
  - infrastructure-lakekeeper.yaml
  - infrastructure-upgrade.yaml
