apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure-platform.yaml
  - infrastructure-monitoring.yaml
  - infrastructure-apps.yaml
  - infrastructure-upgrade.yaml
