---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCxsEHi0+ylr4/+K33lVKOyVxxlkmuE67iO0rWmDntKH1IAw+W33dl/b2ySMxRKili1uy7BVj/FQg556NTPmIYoUzvgDkaUIchbR4hm0opSqAx6ev7eqJie1z7zh61aDnsXM6dPaCelNV/SjirOlyc4S5i/9IVvVPvUpqtGhyAR9ywjVTMXFNmid9nL+24CASu7hSVK52zwrCoUSZdCnNSHP7O+wGF/Dab88cBb0B/Wleh3HnBy5DWECru4/1ybvJG8Hh9AdP7gJpIK6zOdLQCKaUhKBHE2wCcWFacOLR4v3I8oLtJKzS3T6j/Zh46PXjybSGO42YJVzDM48Ln0YkROlKO1b7XQSc3cni5D9XxefqyyEbfxI5e9lnQbKFMbdXC6Nqz2disv+XmBopP7dgbbb7u6qX7OPUcV4sEOwVg7sxyUkyfgzMUpy/VJLN7dnXii0XZHJsTGeCtAIb9xcmA9BarjQ/G8LESFduGPhJ4OSHs/sLUl0D9wjSlQvjHzMdZbD+7QEM1SX0R+VSmxJHm8pBmHIbAZbvFHrpUjfsgUVaiWndIlxCDJN8atP4vyfOtdtqyEhG0plv9iXgE1vJIcfAlX42sYRi/bzLle1O37SLyC1ky5bfagz8u9X1UcvQ3swrsxXpitVX4nYsvt+GoP1qvSY2J2Uu6mY4t9NPBTi2kRfL6w8xlLlRn5N7mibtyNCfBHgWlloF0jfadW2tucgIMOQ8dqEUFN1Xe7rg/7wQ==
    admin-user: AgAlPUYCza3f3IwN4QPOC6QNikzL1ydQv5abv9+zVATpstj4YlPVmLXSVvPmo9bmWheUrtMIo3dp1UHwRF9zr6uFnja6XZeeOoz/Rq8WU2w6RvFewczaGzzkib2F8pwb2JDHVar7wWmSdHd6H8zHlTKv9n/2mR/dJiLh0sUG4PShiarFTxoTUBQol/ERq0h2RoyP09C+3TGPmyhUsw24f29gz88MDK3piOQ3K8yxMljJRMrJfB3JegDXzOaedh98+BmwoMOlqFrq7dEQ1V0bZDsT1hU0qhrP3IqF8JwKOpU2+xTJ/ng59hjLROsDYP5EJVmj0FLNnG4w/Nnlunw5By9pIZF2SU/xk+OHcTbO633g1h4Zcdq71ria7/3MkkI9e0RDt76u/R2eruhsnZ8j5X+oUZCKOZf7/60lXuu8lukrZSuq6DYTe102Y03KktbwXnz4FPnQSa8AIw3GzCxpLRKPPssMitZ/1t/5GoHNB8BkiRWN+IQLxz9aEwyZRJn049kY3zC4wMcIelFMZ2f9CxICJ7ifbdbUY9TxQU01vBJZcW/MVxVsRLeyFDEsExWmnd+c7X9dZL3tqsDtoNfIa84BwrUqFm/zWXfkU4O7mfJ0py1BwzNUX2hKyRklyp+WX+zDhFWdA9i9p5WZlzEd1eJsp28T411++CLSusje+MREepl1K8/OROH276cgQVDh4sgZlFOIlg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
