apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-monitoring-loki-0
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-nvme
  resources:
    requests:
      storage: 50Gi
