apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme
provisioner: topolvm.io
parameters:
  "topolvm.io/device-class": nvme
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: topolvm.io
parameters:
  "topolvm.io/device-class": ssd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
