apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-ssd-service-account
  namespace: local-path-ssd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-ssd-role
rules:
  - apiGroups: [""]
    resources: [nodes, persistentvolumeclaims, configmaps, pods/log]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [endpoints, persistentvolumes, pods]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-ssd-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-ssd-role
subjects:
  - kind: ServiceAccount
    name: local-path-ssd-service-account
    namespace: local-path-ssd
