apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-rustfs-auth.yaml
  - sealed-rustfs-setup.yaml
  - sealed-rustfs-oidc.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ingressroute-s3.yaml
  - ingressroute-console.yaml
