---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-oidc
  namespace: rustfs
spec:
  encryptedData:
    client-secret: AgAnaABrBHffibG2GDghriQXC9i9JO8nlbnLRZUFgnVJucQHOLDaVO6vFUg9p8scQBL+/F6EBLCu8KynCLUdFvzRTd8OY4rJe3W4zuSsABKKySg3k+rLu2L2fbUfju2rIYd4UTKrZbRbaqqCjswy7Oa2NDnMBK9mU3hmKYIGFgrchWMXvjXgbK9Yi9j2B1Ha/9caYS0wk2AHvuScnAnjTZTUct0CnF/wWBeKLW6Rh54KIriVmYk1mc2bs0SlHQiF7gg5jp29TmtTEhDTrgUYE6BAa+8IpTjIKzkXlDfnZNXxt/+jgaVjdgDtxIjxkJ6sJOocVGDNIqu/CxHMhHWZqmKExS2faL4v+JOX2kdZi4Odqpd0Zufbt9eQxtpQgC+SS3flsOIRUlUPdqp4P2wEI7DxTC0doOW27RqO8M4kPbGyrrfHKLgmh9KTYK5Z2w2BHMrGSxQcebBCGbUB6ZeY1xN0ptrMXRdALKGYBzJqz4rS8P/ezfj/edCO127UmWEbjZe9TWHTU2FgQSYvdOoKso1nQVb4Yvu7GlE25UYAsaKw+h+6uBQbubIbf4RaH4wWGB7hDVVgIvxziakxcTEn926vVujNvf8zrgsi0Ky+FidtREA46TAWq6myW7v/08XgI3OgKi43zRDvOLdo3gUdlUfO3OSGE6s1i7UdwfIgsaSQLLCJbSMjLo5oGSMNk7xxGsd1Sf5M7qs1FXuR+QqUtARx/g22g1JGMG1f8DetwojdIIXfDDeqC+l9qTHaMyEW6++NwxLcWhs=
  template:
    metadata:
      name: rustfs-oidc
      namespace: rustfs
    type: Opaque
