---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-auth
  namespace: rustfs
spec:
  encryptedData:
    access-key: AgCpMVPwj0JgrHWIOKAqpvcmnfK9iXXxK3F1/eYFBL5Ogux7o7IWhT+QSgdBx6/TAUPvt2Fy/K9HR/iyVhHzuGjoFAVIbXZwOcvpHsQZtaW9buZxOpGnQ85uh+hfr1APtIYray2fayb5N87dHBJ9qNnZSedgA3WB+vje19uT+g2aJav52SkSwNv8jYHHBxTbxTHfFPYZh4njTACw6efXUnBBL3sXNaInFKBxqG/ZD711qZONsfJ6jNZiuMKQ4c/6gn1W6msmNjznBSpWWpVXSOA9d+axCH0RH76rNLNDoA7cL01YhsvHivDjf5McIX696sYbvVFa5wNkzw9Il73n7K6RhZMxl2v8nWvaEl1R98GjSSnu6TY+LVb/tlfEKUJo1QcyB1bswegE+ZN3NIdwxVman8MT6xkSG6shUaM93SIGZ09gtjs2Nf1pXWHFi48vUAwcCDpVr5AF345LOwPraPZ56B+MMfF5auk8vDaMdmsmYg0RU8TsBgYlv1DPyFK9DCRsoWusVsxxchZE1tkYLDPBCd17psG1aZl9RlyfEcPXWec+6yq7eo7s9T7pOK4yCKiVBHfIgyEVPefumMlPOFm01axGq4S6Tu6jYiN7G/yWVN4wavlpaxw8uHYR57ccJackWLuIYLHRFXbR/MKHZtsDCQW23BkrVFm/9E7AfiV0GQo8+3NyfJfT98Ftq8PtbKD0Ed1iOmzZhFW84A==
    secret-key: AgCj9bFhMscIYXCvjifh9NITTZbtjdDiwWQg8XNbdYjcNT81rkBLeKgCaQpi7Nnsct9Z4khr9D0OdATz9m1XOVa4G85tpsZDME+31QZdt8d/dOo5wtNnuA4VcSaUGfVn52wRsL1Ueea4arY11jYQiGlXR/71XGRbDRPiSjb0XWFLmSm8f1VbVtXnityAnQ5YP1yq6YxqTqjwNSTVVBNQ2AaBMFhKpnZ/mX8Zq2ZWVd7svTzH+k9f2NXWiBhwTdyZ606pyZGc0DKYvk1b1dBPkRaQPF1H2+vBu5lOWOa5tjT5zCnck2iXq8vVNczo5KO6iWtTVMikPjWYgNlEGeDQ8y6xrt15XAP0iGhL5ZIQJltd34NllmKLUYz7TIs4hw0celX9JpQrdcqQtzIFZTr5bq/ktwjuUslzP+j8409YI4gyNiQyfehvKh3tCjUfCWqbpOP9UTgZO3qEsfpwvTyr2LDknX7eF7kQi2NEDEVI6e6kGw7+n5TzdCXfgFGX5xGPrLWJ6fXgNLYaJLjqJTgH9ng7sY7TIjPw91CCwpmoRPvplgCOKVQkBfghHt3dfXm6ynHC683zOBzOLM3sb9ebyxDqGzkrfoBdKg9GPZigKOBCX9GfBIxgE/73nmQ1nGqGhe0QBNl2zMyrhVFW+LVd2AjCE+ZBntjLfq3k70QBJnk8UwQRiHlbLD8qTQ7qV7/gJenhniAaOozf6WSTKLl3wvW7ae9keIqJvBt4fYYOBbFihWkDYIB+Fvb00ikk
  template:
    metadata:
      name: rustfs-auth
      namespace: rustfs
    type: Opaque
