theme: dark

log:
  level: info

server:
  address: tcp://0.0.0.0:9091/

authentication_backend:
  password_reset:
    disable: false
  file:
    path: /config/users.yaml
    password:
      algorithm: argon2id

totp:
  issuer: int.edgedatalab.com
  algorithm: SHA1
  digits: 6
  period: 30

access_control:
  default_policy: deny
  rules:
    - domain: grafana.int.edgedatalab.com
      subject:
        - group:admins
        - group:developers
      policy: two_factor
    - domain: prometheus.int.edgedatalab.com
      subject: group:admins
      policy: two_factor
    - domain: garage.int.edgedatalab.com
      subject: group:admins
      policy: two_factor
    - domain: dagster.int.edgedatalab.com
      subject:
        - group:admins
        - group:developers
      policy: two_factor

    - domain: auth.int.edgedatalab.com
      policy: bypass

session:
  cookies:
    - name: authelia_session
      domain: int.edgedatalab.com
      authelia_url: https://auth.int.edgedatalab.com
      expiration: 1h
      inactivity: 30m
      remember_me: 720h

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /data/db.sqlite3

notifier:
  smtp:
    address: submission://smtp-relay.brevo.com:587
    sender: "EdgeDatalab <noreply@edgedatalab.com>"
    subject: "[EdgeDatalab] {title}"

identity_providers:
  oidc:
    cors:
      endpoints:
        - authorization
        - token
        - userinfo
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: true
