theme: dark

log:
  level: info

server:
  address: tcp://0.0.0.0:9091/

authentication_backend:
  password_reset:
    disable: false
  file:
    path: /config/users.yaml
    password:
      algorithm: argon2id

totp:
  issuer: int.edgedatalab.com
  algorithm: SHA1
  digits: 6
  period: 30

access_control:
  default_policy: deny
  rules:
    - domain: grafana.int.edgedatalab.com
      subject: group:admins
      policy: two_factor
    - domain: garage.int.edgedatalab.com
      subject: group:admins
      policy: two_factor
    - domain: auth.int.edgedatalab.com
      policy: bypass

session:
  cookies:
    - name: authelia_session
      domain: int.edgedatalab.com
      authelia_url: https://auth.int.edgedatalab.com
      expiration: 1h
      inactivity: 30m
      remember_me: 720h

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /data/db.sqlite3

notifier:
  smtp:
    address: submission://REDACTED_SMTP_HOST:587
    sender: "EdgeDatalab <noreply@edgedatalab.com>"
    subject: "[EdgeDatalab] {title}"

identity_providers:
  oidc:
    jwks:
      - key_id: main
        algorithm: RS256
        use: sig
        key: '{{ secret "/secrets-oidc/OIDC_PRIVATE_KEY" }}'
    clients:
      - client_id: garage-ui
        client_name: Garage UI
        client_secret: '{{ secret "/secrets-oidc/GARAGE_UI_CLIENT_SECRET_HASH" }}'
        public: false
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris:
          - https://garage.int.edgedatalab.com/auth/oidc/callback
        scopes:
          - openid
          - email
          - profile
          - groups
        response_types:
          - code
        grant_types:
          - authorization_code
        token_endpoint_auth_method: client_secret_basic
        userinfo_signed_response_alg: none
